### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kavishgr** [vulmon/Vulmap#10]
<img width="1110" alt="Screen Shot 2019-11-05 at 12 26 38" src="https://user-images.githubusercontent.com/45298829/68190844-a72f9900-ffc7-11e9-88e3-874be82ff413.png">

**Comment by kavishgr** [comment]
i deleted the banner() function then it runs without errors.

**Comment by yavuzatlas** [comment]
@HakanBayir
