### ISSUE TITLE
improvement suggestion

### ISSUE THREAD

**Issue by naynivek** [vulmon/Vulmap#11]
Can you improve the Windows Script to make scan on remote computers ?

**Comment by yavuzatlas** [comment]
It's already in our plan. But our current plan is writing it as another tool or script.

**Comment by naynivek** [comment]
oh, great ! I changed your script, make some tests but seems like my complement has some issues, the remote data seems doesn't have the DisplayName property to get values.
but i'm glad to hear that.

**Comment by itilitymsp** [comment]
Been a while but you can run PSExec from sysinternals. to run powershell remotely. https://4sysops.com/archives/use-psexec-and-powershell-together/

**Comment by naynivek** [comment]
Nice, to be honest I don't use this tool anymore since I've changed the company. But thanks bro :)
