### ISSUE TITLE
dpkg-query

### ISSUE THREAD

**Issue by longfeide2008** [vulmon/Vulmap#12]
/bin/sh: dpkg-query: command not found

**Comment by HakanBayir** [comment]
Thanks for yor comment. Which is the linux distribution you get this output?

**Comment by longfeide2008** [comment]
➜  ~ uname -a
Darwin kissy-mac-pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by longfeide2008** [comment]
> Thanks for yor comment. Which is the linux distribution you get this output?

➜  ~ uname -a
Darwin kissy-mac-pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by longfeide2008** [comment]
> 感谢您的评论。您得到此输出的是哪个Linux发行版？

➜  ~ uname -a
Darwin kissy-mac-pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by longfeide2008** [comment]
> Thanks for yor comment. Which is the linux distribution you get this output?

➜  ~ uname -a
Darwin kissy-mac-pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by HakanBayir** [comment]
OS X support is not available in the current version. Therefore, you have received this error.
