### ISSUE TITLE
Doesn't show vulnerabilities in Windows

### ISSUE THREAD

**Issue by Sabir97** [vulmon/Vulmap#26]
When i run Vulmap, it doesn't output the vulnerabilities.
The output i get is:
```
Vulmap started...
Collecting software inventory...
Software inventory collected
Vulnerability scanning started...
Checked 89 items
Vulmon.com Api returned message:
Done.
```

**Comment by wizardlevel9** [comment]
I believe that the Vulmon API is not working.

 Vulmap started...
Collecting software inventory...
VERBOSE: Reading installed software from registry.
Software inventory collected
Saving software inventory to inventory.json...
Vulnerability scanning started...
VERBOSE: Submitting software to vulmon.com api, batch '0' of '2'.
VERBOSE: POST https://vulmon.com/scannerapi_vv211 with -1-byte payload
Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At C:\Users\Administrator\Desktop\vulmap-windows.ps1:227 char:14
+             (Invoke-WebRequest @webRequestSplat).Content | ConvertFro ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by yavuzatlas** [comment]
Thanks for reporting this issue. I fixed it. Can you check it again please @Sabir97 @wizardlevel9?

**Comment by Sabir97** [comment]
@yavuzatlas No, it's still not showing the vulnerabilities.
![image](https://user-images.githubusercontent.com/52837091/210174123-c5279ac3-83bf-4b4c-ab12-3173792e9cea.png)

**Comment by yavuzatlas** [comment]
What's your operating system?

**Comment by Sabir97** [comment]
My OS is: Windows 10

**Comment by yavuzatlas** [comment]
I tested it on Windows 10 and it worked fine. If it doesn't find any vulnerabilities when you run it, that means there aren't any known vulnerabilities in the vulnerability database that match the programs in your environment.

**Comment by yavuzatlas** [comment]
The issue has been fixed.
