### ISSUE TITLE
https://vulmon.com/scannerapi_vv211 down

### ISSUE THREAD

**Issue by P6g9YHK6** [vulmon/Vulmap#33]
![image](https://github.com/vulmon/Vulmap/assets/17877371/711a2569-d7b1-450f-b226-f3189825516f)

**Comment by P6g9YHK6** [comment]
Came back up after going into an error 500.

**Comment by P6g9YHK6** [comment]
![image](https://github.com/vulmon/Vulmap/assets/17877371/a7bbd4f4-5527-4601-b598-afe88e2e66cf)

**Comment by yavuzatlas** [comment]
Fixed. Thanks.
