### ISSUE TITLE
Error not have response

### ISSUE THREAD

**Issue by RDFonseca82** [vulmon/Vulmap#36]
Invoke-WebRequest : O servidor remoto devolveu um erro: (403) Proibido.
At C:\Users\RDFonseca\Desktop\vulmap-windows.ps1:188 char:20
+         $request = Invoke-WebRequest @webRequestSplat
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by RDFonseca82** [comment]
Every time in all computers i receive this message

![vulnmap](https://github.com/user-attachments/assets/2047a258-a038-41dc-ba7b-52e48ac9aeaa)

**Comment by yavuzatlas** [comment]
Hi. This means Vulmap worked successfully but couldn't find any vulnerability in your computers.
