### ISSUE TITLE
Why no automated testing? Travis CI, CircleCI, AppVeyor, Azure Pipelines, etc?

### ISSUE THREAD

**Issue by cclauss** [vulmon/Vulmap#5]
It would be cool to see what Vulmap can find in these free testing environments.

https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

**Comment by yavuzatlas** [comment]
Hi,
Is it possible for you to give some more detail?

**Comment by cclauss** [comment]
There are [a lot of great tools](https://github.com/marketplace/category/continuous-integration) that would run free tests on every pull request.  This would make it easier to find and fix bugs in Vulmap.
